version: "3.8"
services:
  testing-app:
    container_name: just-a-testing-app
    build: ./
    restart: on-failure
    command: sh -c "yarn install && yarn start"
    volumes:
      - "./package.json:/usr/app/package.json"
      - "./yarn.lock:/usr/app/yarn.lock"
      - "./tsconfig.json:/usr/app/tsconfig.json"
      - "./src:/usr/app/src"
    environment:
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_POLLINTERVAL: 3000
